apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-money-api
  labels:
    app: go-money-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-money-api
  template:
    metadata:
      labels:
        app: go-money-api
    spec:
      containers:
      - name: go-money-api
        image: sirpaulx/go-money-api:go-money-api
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: go-money-api-service
spec:
  selector:
    app: go-money-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 32000
  type: NodePort
