apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    http {
        limit_req_zone $binary_remote_addr zone=req_limit_per_ip:10m rate=5r/m;

        server {
            listen 80;

            location / {
                limit_req zone=req_limit_per_ip burst=10 nodelay;
                proxy_pass http://go-money-api-service:80;
            }
        }
    }
