name: Deploy to K3s

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      AWS_USER: ubuntu
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t sirpaulx/go-money-api:go-money-api .
          docker push sirpaulx/go-money-api:go-money-api

      - name: Copy Kubernetes manifests to EC2
        uses: easing/scp-action@v2
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.AWS_USER }}
          key: ${{ env.EC2_SSH_KEY }}
          port: 22
          local: "k8s-deployment.yaml,nginx-deployment.yaml"
          remote: /home/ubuntu/

      - name: Deploy to K3s on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.AWS_USER }}
          key: ${{ env.EC2_SSH_KEY }}
          script: |
            kubectl apply -f /home/ubuntu/k8s-deployment.yaml -f /home/ubuntu/nginx-deployment.yaml
            kubectl rollout restart deployment/go-money-api
