name: Deploy to K3s

on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      AWS_USER: ubuntu
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t sirpaulx/go-money-api:go-money-api-$GITHUB_SHA .
        docker push sirpaulx/go-money-api:go-money-api-$GITHUB_SHA

    - name: Deploy to K3s on EC2
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ env.EC2_HOST }}
        username: ${{ env.AWS_USER }}
        key: ${{ env.EC2_SSH_KEY }}
        script: |
          scp -o StrictHostKeyChecking=no -i ${{ env.EC2_SSH_KEY }} ./*.yaml ${{ env.AWS_USER }}@${{ env.EC2_HOST }}:/home/ubuntu/
          kubectl apply -f /home/ubuntu/.
          kubectl rollout restart deployment/go-money-api
